version: "3"
services:
  redis:
    container_name: redis
    image: redis:5-alpine
    volumes:
      - ./backend/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./backend/redis/data:/data
    command: redis-server /usr/local/etc/redis/redis.conf
  backend:
    container_name: backend
    build: backend
    depends_on:
      - redis
    links:
      - redis
  frontend:
    container_name: frontend
    build: frontend
    ports:
      - 8080:80
      - 8081:8081
    links:
      - backend
